### ISSUE TITLE
once('value') never resolves

### ISSUE THREAD

**Issue by austin43** [sebasgarcep/firebase-admin-mock#1] opened 2017-07-13 20:41 UTC
```
// test.js

sinon.stub(config,'getFirebaseInstance')
  .returns(newAdminRoot()
  .initializeApp({databaseUrl:'fake.firebase.com'}))
```

```
// query.js

const snapshot = await config
  .getFirebaseInstance()
  .database()
  .ref()
  .once('value')
```

The promise seems to never resolve and mocha times out.  This call works when leaving the call unmocked.  Am I doing something incorrectly?

**Comment by sebasgarcep** [comment] 2017-07-17 14:24
Is this a typo?
```
  .returns(newAdminRoot()
```

I guess it should be:
```
  .returns(new AdminRoot()
```

If that's not the cause of the problem, could you provide a minimal example that runs without modifications so I can solve the issue? Also sorry for taking a while to answer.

**Comment by Karn** [comment] 2017-07-23 05:42
Just chiming in, I think I've managed to reproduce it fairly reliably. Below is a minimal example. I suspect it only happens when the key does not exist.

```javascript
import { AdminRoot } from 'firebase-admin-mock'

const admin = new AdminRoot()
admin.database().setMockData({ foo: 'bar' })

admin.database().ref('test').once('value').then((dataSnapshot) => {
    console.log('Complete! ' + dataSnapshot.key)
}).catch((error) => {
    console.log('Error: ' + error.message)
})
```

On another note, this is an awesome mocking of the firebase library. Thanks for spending time to make it!

**Comment by sebasgarcep** [comment] 2017-07-23 16:17
Thanks @Karn!

About the issue, I've noticed your code is missing:
```javascript
admin.initializeApp({
  ...config
})
```
I think Firebase requires configuring `admin` with this call before you do anything at all, so failing for this reason is expected.

I'm working on a PR to export a `defaultConfig` to use for testing purposes when you don't care about which configuration is used. It will work like this:

```javascript
const { AdminRoot, defaultConfig } = require('firebase-admin-mock');

const admin = new AdminRoot();
admin.initializeApp(defaultConfig);

// ... rest of your code
```

I'm also going to document this behaviour as I notice it is a possible pain point. Is this alright?

On the other hand, even when `admin.initializeApp()` is used in @Karn's code it displays nothing. I'm opening a new issue for this.

Again, thanks for all your help!

**Comment by sebasgarcep** [comment] 2017-07-23 16:42
#2 adds docs and exports `defaultConfig`. Closing this issue in favor of #3. @austin43 @Karn

**Closed** 2017-07-23 16:42 UTC

**Comment by austin43** [comment] 2017-07-28 00:09
Thanks for the fix! Awesome library.
